# Generated by Django 4.1.5 on 2023-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("DepartmentId", models.AutoField(primary_key=True, serialize=False)),
                ("DepartmentName", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("EmployeeId", models.AutoField(primary_key=True, serialize=False)),
                ("EmployeeName", models.CharField(max_length=500)),
                ("Department", models.CharField(max_length=500)),
                ("DateOfJoining", models.DateField()),
                ("PhotoFileName", models.CharField(max_length=500)),
            ],
        ),
    ]
